/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Nick
 */
public class Home extends javax.swing.JPanel {

    /**
     * Creates new form Home
     */
    String adminPass;
    
    public Home() {
        initComponents();
        jWrongPasswordLabel.setVisible(false);
        
        adminPass = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jNewPlayerButton = new javax.swing.JButton();
        jReturningPlayerButton = new javax.swing.JButton();
        jAdminButton = new javax.swing.JButton();
        jAdminPassword = new javax.swing.JPasswordField();
        jWrongPasswordLabel = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welkom bij Full House");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<html>Selecteer in het menu de reden dat U gebruik maakt van dit programma om bij Uw  opties te komen. Als U gebruik wilt maken <br>van de administratieve opties, moet U eerst op deze pagina een wachtwoord invullen.");

        jNewPlayerButton.setText("Ik ben een nieuwe speler");
        jNewPlayerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNewPlayerButtonActionPerformed(evt);
            }
        });

        jReturningPlayerButton.setText("Ik ben een terugkomende speler");

        jAdminButton.setText("Ik ben een administrator");
        jAdminButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAdminButtonMouseClicked(evt);
            }
        });

        jWrongPasswordLabel.setForeground(new java.awt.Color(200, 0, 0));
        jWrongPasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jWrongPasswordLabel.setText("Het wachtwoord dat U ingevuld heeft is incorrect.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jWrongPasswordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jAdminPassword)
                                    .addComponent(jNewPlayerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))
                                .addGap(92, 92, 92)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jReturningPlayerButton, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jAdminButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNewPlayerButton)
                    .addComponent(jReturningPlayerButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAdminButton)
                    .addComponent(jAdminPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jWrongPasswordLabel)
                .addContainerGap(320, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jNewPlayerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNewPlayerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNewPlayerButtonActionPerformed

    private void jAdminButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAdminButtonMouseClicked
        String enteredPass = jAdminPassword.getText();
        if (enteredPass.equals(adminPass)){
            // XXX: Fix dit. Referentie staat onderaan de Full House class.
            // FullHouse.setTab("Admin");
        } else {
            jWrongPasswordLabel.setVisible(true);
        }
    }//GEN-LAST:event_jAdminButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAdminButton;
    private javax.swing.JPasswordField jAdminPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jNewPlayerButton;
    private javax.swing.JButton jReturningPlayerButton;
    private javax.swing.JLabel jWrongPasswordLabel;
    // End of variables declaration//GEN-END:variables
}
