/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

/**
 *
 * @author Nick
 */
public class SelectView extends javax.swing.JPanel {

    /**
     * Creates new form SelectView
     */
    public SelectView() {
        initComponents();
        initPlayers();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTablePlayer7 = new javax.swing.JLabel();
        jTablePlayer2 = new javax.swing.JLabel();
        jTablePlayer8 = new javax.swing.JLabel();
        jTablePlayer3 = new javax.swing.JLabel();
        jTablePlayer1 = new javax.swing.JLabel();
        jTablePlayer5 = new javax.swing.JLabel();
        jTablePlayer4 = new javax.swing.JLabel();
        jTablePlayer6 = new javax.swing.JLabel();

        jTablePlayer7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTablePlayer7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTablePlayer7.setText("Speler7");

        jTablePlayer2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTablePlayer2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTablePlayer2.setText("Speler2");

        jTablePlayer8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTablePlayer8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTablePlayer8.setText("Speler8");

        jTablePlayer3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTablePlayer3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTablePlayer3.setText("Speler3");

        jTablePlayer1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTablePlayer1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTablePlayer1.setText("Speler1");

        jTablePlayer5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTablePlayer5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTablePlayer5.setText("Speler5");

        jTablePlayer4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTablePlayer4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTablePlayer4.setText("Speler4");

        jTablePlayer6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTablePlayer6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTablePlayer6.setText("Speler6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTablePlayer7, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 295, Short.MAX_VALUE)
                        .addComponent(jTablePlayer8, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTablePlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTablePlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTablePlayer5, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTablePlayer6, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTablePlayer3, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTablePlayer4, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTablePlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTablePlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTablePlayer3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTablePlayer4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTablePlayer5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTablePlayer6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(114, 114, 114)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTablePlayer7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTablePlayer8, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jTablePlayer1;
    private javax.swing.JLabel jTablePlayer2;
    private javax.swing.JLabel jTablePlayer3;
    private javax.swing.JLabel jTablePlayer4;
    private javax.swing.JLabel jTablePlayer5;
    private javax.swing.JLabel jTablePlayer6;
    private javax.swing.JLabel jTablePlayer7;
    private javax.swing.JLabel jTablePlayer8;
    // End of variables declaration//GEN-END:variables

    private void initPlayers() {
        
    }
}
